name: news_app_clean_architecture
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # State Management
  flutter_bloc: ^8.1.6
  # A Dart package that helps to implement value based equality
  equatable: ^2.0.5
  # Simple direct Service Locator
  get_it: ^7.7.0
  # DateFormat
  intl: ^0.19.0
  # Database
  floor: ^1.5.0
  floor_generator: ^1.5.0
  # Networking
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.11
  # Hooks
  flutter_hooks: ^0.20.5
  # To load and cache network images.
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
